version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    expose:
      - "5000"
    deploy:
      replicas: 3
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/ssl/private:/etc/ssl/private
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
