version: "3.8"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.web
        expose:
            - "5000"
        deploy:
            replicas: 3
        restart: always

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80" 
        depends_on:
            - web
        restart: always
