version: "3.8"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.web
        expose:
            - "5000"
        deploy:
            replicas: 3

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./selfsigned.crt:/etc/ssl/certs/selfsigned.crt
            - ./selfsigned.key:/etc/ssl/private/selfsigned.key
            - ./nginx.conf:/etc/nginx/nginx.conf
        restart: always
