version: "3"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.web
        ports:
            - "5000:5000"
        depends_on:
            - redis
            - db
        environment:
            - REDIS_HOST=redis

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    db:
        image: postgres:latest
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=flask_db
        ports:
            - "5431:5432"
