services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.web
        expose:
            - "5000"
        deploy:
            replicas: 3

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - web