name: Flask CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - 
        name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.30.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - 
        name: Build and run tests
        run: |
          cd lab-5
          docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
          docker-compose -f docker-compose.test.yml down

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - 
        name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - 
        name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no abalonem@37.230.157.15 "
            cd CloudInfrastructureServices/lab-5
            git pull
            docker-compose -f docker-compose.yml up -d
          "

      - 
        name: Run Migration Script
        run: |
          ssh -o StrictHostKeyChecking=no abalonem@37.230.157.15 "
            cd CloudInfrastructureServices/lab-5
            chmod +x migration.sh
            ./migration.sh
          "
